### ISSUE TITLE
latest statuschecker processing output.xml from 4.0.1 (probably also from 4.0.0) will strip sourcename attribute

### ISSUE THREAD

**Issue by rasjani** [robotframework/statuschecker#30]
My output log as few kw entries like this:

```
<kw name="Wait for Running Runlevel" library="suite_keywords" sourcename="Wait for ${runlevel} Runlevel">
```

When robotstatuschecker is executed against the file, sourcename attribute is completely stripped from outfile.

**Comment by pekkaklarck** [comment]
This bug could actually be in Robot itself. Could you test does same happen with `rebot --output new.xml orig.xml`?

**Comment by rasjani** [comment]
@pekkaklarck Looks like it is. Running rebot will remove  `sourcename` attrib.

**Comment by aaltat** [comment]
Will close because this is a bug in Robot side and not in this project.

**Comment by pekkaklarck** [comment]
Need to report an issue to Robot's tracker about this. I can do that later if you don't do it first.
