### ISSUE TITLE
Robot logger.error(''Message") is not supported by statuschecker

### ISSUE THREAD

**Issue by aaltat** [robotframework/statuschecker#7]
If I have library which does this: 
```
except Exception as error:
            logger.error('Received exception: %s' % error)
```
And when I have test that has this:
```
[Documentation]
    ...    LOG 3:9    ERROR Received exception: 'NoneType' object has no attribute 'quit'
```
Then the correct level is not matched, instead log says it defaults to INFO level:
```
Keyword 'SeleniumLibrary.Close All Browsers' (index 3) message 9 has wrong level. 

Expected: INFO 
Actual: ERROR
```
By looking the code, the bug could be in here: https://github.com/robotframework/statuschecker/blob/master/robotstatuschecker.py#L136 Would it be sufficient to add `ERROR` in the list and write a test for it?

**Comment by pekkaklarck** [comment]
Good catch. User specified ERROR messages are a pretty new feature in RF and apparently not needed earlier by StatusChecker. The proposed fix sounds good.
